package gridmap;

import java.util.*;

import solver.*;

public class GridmapState implements State {
	private String name;
	private double x;
	private double y;
	public static final String[] CITY_NAMES = {
		"Reasnor",
		"Satanta",
		"Brayton",
		"Walkersville",
		"Bingham Farms",
		"Enumclaw",
		"Blountsville",
		"Graettinger",
		"Waltonville",
		"Gasquet",
		"McAlester",
		"Salineno North",
		"Tecolotito",
		"Muniz",
		"Colorado Acres",
		"Maplewood",
		"Shade Gap",
		"Westcliffe",
		"Mayville",
		"Rockport",
		"Lake Almanor",
		"Blooming Prairie",
		"Hitchcock",
		"Gwynn",
		"North Johns",
		"Neshkoro",
		"Blackstone",
		"Hubbard Lake",
		"Bainville",
		"Sherando",
		"Flagler",
		"Finzel",
		"Clear Creek",
		"Antelope",
		"Baird",
		"Rivesville",
		"Abercrombie",
		"Ilwaco",
		"Upham",
		"Lyndonville",
		"Luttrell",
		"Rodey",
		"North Escobares",
		"La Liga",
		"Birdsboro",
		"Little York",
		"Fanshawe",
		"Horsham",
		"Flowery Branch",
		"Promised Land",
		"Illiat",
		"Margat",
		"Curbigny",
		"Attiches",
		"Calais",
		"Chesnois",
		"Moyemont",
		"Colleret",
		"Beaufresne",
		"Sery",
		"Lanteuil",
		"Blendecques",
		"Concourson",
		"Troisfontaines",
		"Bettviller",
		"Perville",
		"Treux",
		"Castrie",
		"Grateloup",
		"Cros",
		"Haget",
		"Naucelle",
		"Guerande",
		"Georfans",
		"Auverse",
		"Buissoncourt",
		"Denier",
		"Bidache",
		"Boucard",
		"Vittarville",
		"Clermain",
		"Barcelonnette",
		"Gouloux",
		"Bayecourt",
		"Chevillele",
		"Courant",
		"Rouhling",
		"Virolle",
		"Roudouallec",
		"Senades",
		"Noaillat",
		"Lez",
		"Tournoux",
		"Coulangé",
		"Colognac",
		"Bourgeade",
		"Lavalade",
		"Gohory",
		"Valle",
		"Bazolles",
		"Moyancon",
		"Carriona",
		"Tugaduaya",
		"Payo",
		"Chillaví",
		"Chila",
		"Sakaim",
		"Pechiche",
		"Chacapamba",
		"Tsentzakentza",
		"Campanita",
		"Pucallpa",
		"Pingulmí",
		"Angochahua",
		"Dubliay",
		"Loyala",
		"Ceuceda",
		"Chalay",
		"Shud",
		"Pichaví",
		"Mulaló",
		"Capricho",
		"Secoya",
		"Collasay",
		"Ramosguaico",
		"Chonta",
		"Chalua",
		"Jovita",
		"Pucala",
		"Enriqueta",
		"Cedropamba",
		"Pangor",
		"Planado",
		"Jaguito",
		"Bunques",
		"Curitroje",
		"Calabria",
		"Portete",
		"Etsa",
		"Providencia",
		"Tinoco",
		"Entzacua",
		"Manuales",
		"Paccha",
		"Dacte",
		"Petrillo",
		"Capsol",
		"Central",
		"Novillo",
		"Membrillo",
		"Igundu",
		"Senegeza",
		"Mkumba",
		"Likumbura",
		"Kolasingo",
		"Nyakabanya",
		"Magagura",
		"Linda",
		"Msomalo",
		"Kikoboga",
		"Waleni",
		"Mesaula",
		"Chimbe Chimbe",
		"Kilosa",
		"Luega",
		"Mamukara",
		"Ndagwasa",
		"Chuini",
		"Mobwani",
		"Mbarangandu",
		"Kanderema",
		"Buyenzi",
		"Kwa Mhinda",
		"Kipororo",
		"Mbemba",
		"Kihogoni",
		"Mubweza",
		"Imesera",
		"Nyakawanga",
		"Mpapura",
		"Enaboishu",
		"Mwambas",
		"Nala",
		"Materawe",
		"Chanika",
		"Mwakubiringa",
		"Majingani",
		"Chiungutwa",
		"Nyatama",
		"Kiungule",
		"Ndembera",
		"Mihambwe",
		"Kwoguni",
		"Dareda",
		"Shindoni",
		"Usase",
		"Kijeba",
		"Kitunduini",
		"Chukwani",
		"Malijoni",
		"Bản Thuc",
		"Ban Phi Ko",
		"Cam Kam",
		"Plei Néo",
		"Nho Quạn",
		"Vi Ho Lak",
		"Bình Hà",
		"Xóm Bau",
		"Bo Loung",
		"Hoi Diem",
		"Nà Ket",
		"Qui Hậu",
		"Khe Vai",
		"Buon Blanh",
		"Tân Linh",
		"Lang Duoc",
		"Tu Duon",
		"Chành Lỳ",
		"Hai An",
		"Na Nam Nhang",
		"Quang Ha",
		"Minh Cát",
		"Xom Ta Song",
		"Ban Houei Phay",
		"Bu Glong",
		"Tuong Car",
		"Thổ Hoàng",
		"Ban Lang Cai",
		"Suối Bang",
		"Van Thủy",
		"Ngoc Hot",
		"Nậm Kan",
		"Quang Giu",
		"Qui Trình",
		"Son Lang",
		"Cây Ða",
		"Hạ Trang",
		"Tri Nai Ngoai",
		"Cay Chanh",
		"Ngan Kheo",
		"Cam Lau",
		"Na Koue",
		"Bao Sau",
		"Tien Lang",
		"Thương Trung",
		"Cam Ranh Port",
		"Suyut",
		"Ban Ngo",
		"Hon Khoi",
		"Gio Linh",
		"Oiwake",
		"Ishihama",
		"Anamizu",
		"Fujaku",
		"Nagasaka",
		"Kurino",
		"Kasada-naka",
		"Matsugi",
		"Natsuyama",
		"Hamada",
		"Shimomura",
		"Sakaore",
		"Kuratami",
		"Shiraide",
		"Nara",
		"Suizawa",
		"Minami-tomamu",
		"Fujino",
		"Yamato",
		"Okkia",
		"Nigonki-machi",
		"Mugigaura",
		"Naka-kuwahara",
		"Hama",
		"Shichiku",
		"Jingūji",
		"Singū",
		"Uenochi",
		"Samejima",
		"Kaigarazuka",
		"Hiroto",
		"Kawara",
		"Togawamachi",
		"Kawanoishi",
		"Dira",
		"Yonōzu",
		"Yumugi",
		"Takayashiki",
		"Karatu",
		"Kitadai",
		"Shimo-kenoboribetsu",
		"Asakuragi",
		"Yotsu-no-ura",
		"Takada",
		"Omonawa",
		"Kosawa",
		"Suga",
		"Oshirobayashi",
		"Naka-wada",
		"Yudanaka",
		"Cerdillo",
		"Mesiego",
		"Todolella",
		"Biota",
		"Alberite",
		"Moimenta",
		"Orillares",
		"Miravet",
		"Cruzul",
		"Sardina",
		"Urriales",
		"Congosto",
		"Loredo",
		"Suarbol",
		"Melendreros",
		"Castromayor",
		"Urrestilla",
		"Sanjurjo",
		"Roblido",
		"Panizal",
		"Laya",
		"Tarnas",
		"Villagrille",
		"Urrutia",
		"Rufrancos",
		"Miyeres",
		"Bonillos",
		"Ardaiz",
		"Eransus",
		"Borines",
		"Orante",
		"Salamir",
		"Canredondo",
		"Porzuna",
		"Abezames",
		"Quart",
		"Peones",
		"Gayatos",
		"Costamar",
		"Castillonroy",
		"Berveraso",
		"Bisjueces",
		"Mocanal",
		"Bohiles",
		"Limones",
		"Villamanta",
		"Torla",
		"Vinseiro",
		"Ustara",
		"Tordillos",
		"Bin Gamarsh",
		"Shoowaya",
		"Quwā",
		"Aş Şaḩan",
		"Barud",
		"Mu‘arran",
		"Qufl",
		"Tharwa",
		"Al ‘Iyaynah",
		"Suwayrikīyah",
		"Imhaish",
		"Ar Rabaḑ",
		"Jawzān",
		"Al-Tuwaithir",
		"Al Qarī",
		"Al Quşayr",
		"Āl ‘Āyiḑ",
		"Sayr",
		"El Medina",
		"Adh Dhirwayin",
		"Gabouk",
		"Hadaba",
		"Ad Dīrīyah",
		"Husainiyah",
		"Fugana",
		"Malham",
		"Li‘li‘",
		"Muwaih Hakran",
		"Şobh",
		"Suwada",
		"Al-Hajar",
		"Sharūrah",
		"Aş Şufayrī",
		"Mujamma‘ al Ḩadīthah",
		"Wa‘lān",
		"Sa‘diya",
		"Khulayş",
		"Yanbu‘",
		"Al Wuqīd",
		"Ar Rayn",
		"Al Milḩah",
		"Al Khamrah",
		"Al Ghaḑyā’",
		"Miná",
		"Hifna",
		"Umm ‘Amāyin",
		"Qaşr Ḩillīyah",
		"Aḑ Ḑal‘ah",
		"Thādig",
		"Khasaa",
		"Kleppestø",
		"Hennseid",
		"Sognefjord",
		"Aaknes",
		"Trolfjord",
		"Vikleira",
		"Ilstad",
		"Eikeland",
		"Vike",
		"Gullstein",
		"Riaanaes",
		"Vigrestad",
		"Alset",
		"Bufloen",
		"Branddal",
		"Kvitno",
		"Stavik",
		"Surna",
		"Slydalen",
		"Vestgard",
		"Ovrein",
		"Tokkstad",
		"Rosendal",
		"Frekhaug",
		"Ausland",
		"Hoffstad",
		"Finnbekken",
		"Balangrud",
		"Dybo",
		"Kjetsaa",
		"Blindvaagen",
		"Stave",
		"Okkenhaug",
		"Bolle",
		"Falkanger",
		"Tisnes",
		"Drangsholt",
		"Gavlen",
		"Vistad",
		"Vikjorda",
		"Andopen",
		"Tofsrud",
		"Nordskar",
		"Sillvik",
		"Bratli",
		"Steinshamn",
		"Revholt",
		"Lovold",
		"Mydland",
		"Bergsvik",
		"Palumbo",
		"Ponzano",
		"Palombaio",
		"Caltana",
		"Codovilla",
		"Sperone",
		"Carasco",
		"Caprile",
		"Gropada",
		"Ro",
		"Saponara",
		"Formigara",
		"Roversano",
		"Laghi",
		"Gigliola",
		"Chabaud",
		"Intermesoli",
		"Borghi",
		"Cadignano",
		"Caidate",
		"Montebabbio",
		"Capena",
		"Cantone",
		"Loro",
		"Brossasco",
		"Collevecchio",
		"Pierle",
		"Vegia",
		"Porle",
		"Cintano",
		"Summonte",
		"Gamalero",
		"Barkovlje",
		"Borgomale",
		"Chambave",
		"Palagianello",
		"Roncà",
		"Crustumerium",
		"Bribano",
		"Porrona",
		"Vinigo",
		"Terisso",
		"Mevale",
		"Rocciano",
		"Sanguarzo",
		"Alianello",
		"Droneretto",
		"Brusuglio",
		"Gavriago",
		"Ciambave"
	};
	
	public GridmapState(GridmapState room) {
		this.name = room.getName();
		this.x = room.getX();
		this.y = room.getY();
	}
	
	public GridmapState(String name) {
		this.name = name;
		this.x = 0.0;
		this.y = 0.0;
	}
	
	public GridmapState(String name, double x, double y) {
		this.name = name;
		this.x = x;
		this.y = y;
	}
	
	public static String randomName() {
		return CITY_NAMES[new Random().nextInt(CITY_NAMES.length)];
	}
	
	public String getName() {
		return name;
	}
	
	public double getX() {
		return x;
	}
	
	public double getY() {
		return y;
	}
	
	public double distanceTo(GridmapState room) {
		return Math.sqrt(Math.pow(Math.abs(x - room.getX()), 2) + Math.pow(Math.abs(y - room.getY()), 2));
	}
	
	@Override
	public String toString() {
		return name + " (" + String.format("%.2f", x) + ", " + String.format("%.2f", y) + ")";
	}

	@Override
	public int hashCode() {
		final int prime = 36;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		long temp;
		temp = Double.doubleToLongBits(x);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(y);
		result = prime * result + (int) (temp ^ (temp >>> 32));

		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof GridmapState))
			return false;
		GridmapState other = (GridmapState) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (Double.doubleToLongBits(x) != Double.doubleToLongBits(other.x))
			return false;
		if (Double.doubleToLongBits(y) != Double.doubleToLongBits(other.y))
			return false;
		return true;
	}
}
